### ISSUE TITLE
Volume control

### ISSUE THREAD

**Issue by akastrin** [miklhh/i3blocks-config#1]
Hi,

I wonder how do you change sound level? If I understand correctly your script, you only display volume level.

Best, Andrej

**Comment by miklhh** [comment]
Hi!

You can bind different keys to let i3 issue volume control settings on your system through `~/.config/i3/config`. In the following example, I have bound my laptop special keys (VolumeUp, VolumeDown and Mute) to invoke and handle sound level and mute functionality through a utility called [pamixer](https://github.com/cdemoulins/pamixer).

```
# User-added function keys:
bindsym XF86AudioMute         exec --no-startup-id pamixer -t     && pkill -RTMIN+1 i3blocks
bindsym XF86AudioLowerVolume  exec --no-startup-id pamixer -d 3   && pkill -RTMIN+1 i3blocks
bindsym XF86AudioRaiseVolume  exec --no-startup-id pamixer -i 3   && pkill -RTMIN+1 i3blocks
```

If you don't have pamixer installed, this second example illustrates control of sound directly through the ALSA cli-tool and does not require any extra packages installed:
```
bindsym XF86AudioRaiseVolume exec --no-startup-id amixer -M -q -D pulse sset Master 2%+ && pkill -RTMIN+1 i3blocks
bindsym XF86AudioLowerVolume exec --no-startup-id amixer -M -q -D pulse sset Master 2%- && pkill -RTMIN+1 i3blocks
bindsym XF86AudioMute exec --no-startup-id amixer -q -D pulse sset Master toggle && pkill -RTMIN+1 i3blocks
```

Does this answer your question? Feel free to ask if anything is unclear.

**Comment by akastrin** [comment]
Thanks, that helps a lot.

Andrej
